# Generated by Django 4.1.2 on 2022-11-04 15:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=jsonfield.fields.JSONField(blank=True, default='', null=True),
        ),
    ]
