# Generated by Django 4.1.2 on 2023-01-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='captain_changes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vice_captain_changes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
