# Generated by Django 4.1.2 on 2023-02-16 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_change'),
        ('users', '0006_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orange_cap',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orange_cap', to='core.player'),
        ),
        migrations.AddField(
            model_name='profile',
            name='purple_cap',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purple_cap', to='core.player'),
        ),
    ]
