# Generated by Django 4.1.2 on 2023-02-23 05:43

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_daily_prediction2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daily_prediction2',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bonus_points',
            field=jsonfield.fields.JSONField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='daily_prediction',
            field=jsonfield.fields.JSONField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=jsonfield.fields.JSONField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points_description',
            field=jsonfield.fields.JSONField(blank=True, default='{}', null=True),
        ),
    ]
