# Generated by Django 4.1.2 on 2023-03-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_profile_prediction_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reference",
            field=models.TextField(blank=True, null=True),
        ),
    ]
