# Generated by Django 4.1.2 on 2023-03-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_prediction_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_created_team',
            field=models.BooleanField(default=False),
        ),
    ]
