# Generated by Django 4.1.2 on 2023-03-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_has_created_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='connected_accounts',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
