# Generated by Django 4.1.2 on 2023-04-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_profile_prediction_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
