# Generated by Django 4.1.2 on 2022-11-04 15:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_match_has_completed_match_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matches',
            field=jsonfield.fields.JSONField(blank=True, default='', null=True),
        ),
    ]
