# Generated by Django 4.1.2 on 2022-11-04 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player_matches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_match_completed', models.IntegerField(default=0)),
                ('is_any_match_live', models.BooleanField(default=False)),
                ('match_live', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_match', to='core.match')),
            ],
        ),
    ]
