# Generated by Django 4.1.2 on 2022-11-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_player_matches_player_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
