# Generated by Django 4.1.2 on 2022-11-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_player_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='points',
            new_name='bat_points',
        ),
        migrations.AddField(
            model_name='player',
            name='bowl_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='total_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
