# Generated by Django 4.1.2 on 2023-02-17 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_match_date_player_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
